DjangoProject/DjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('profileapp.urls', namespace='profile')),
]

DjangoProject/profileapp/urls.py
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog
from . import views

app_name = 'profile'

urlpatterns = [
    path('<int:pk>/profile/', views.ShowProfile.as_view(), name='showprofile'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('<int:pk>/update/', views.UpdateProfile.as_view(), name='updateprofile'),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('', views.main_page_redirect, name='redirect-page')
]

DjangoProject/profileapp/models.py
import json

from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Profile(models.Model):
    """Profile model"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255, blank=True, null=True)
    last_name = models.CharField(max_length=255, blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    biography = models.TextField(blank=True, null=True)
    contacts = models.CharField(max_length=255, blank=True, null=True)
    edit_ip = models.GenericIPAddressField(blank=True, null=True)

    def __str__(self):
        return self.user.username


class Notes(models.Model):
    """Model to insert notes"""
    note = models.CharField(max_length=255)


class WebRequest(models.Model):
    """Model for saving requests"""
    time = models.DateTimeField(auto_now_add=True)
    host = models.CharField(max_length=1000)
    path = models.CharField(max_length=1000)
    method = models.CharField(max_length=50)
    uri = models.CharField(max_length=2000)
    status_code = models.IntegerField()
    user_agent = models.CharField(max_length=1000, blank=True, null=True)
    remote_addr = models.GenericIPAddressField()
    remote_addr_fwd = models.GenericIPAddressField(blank=True, null=True)
    meta = models.TextField()
    cookies = models.TextField(blank=True, null=True)
    get = models.TextField(blank=True, null=True)
    post = models.TextField(blank=True, null=True)
    raw_post = models.TextField(blank=True, null=True)
    is_secure = models.BooleanField()
    is_ajax = models.BooleanField()
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)


def dumps(value):
    return json.dumps(value, default=lambda o: None)

DjangoProject/profileapp/forms.py
from django import forms
from django.contrib.admin.widgets import AdminDateWidget
from .models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ('edit_ip', 'user')
        widgets = {
            'date_of_birth': AdminDateWidget()
        }

DjangoProject/profileapp/views.py
from django.views.generic import DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from .models import Profile
from .forms import ProfileForm


# Create your views here.
class ShowProfile(LoginRequiredMixin, DetailView):
    """Detail view function"""
    model = Profile
    login_url = '/accounts/login/'
    template_name = 'show_profile.html'
    redirect_field_name = 'login'


class UpdateProfile(LoginRequiredMixin, UpdateView):
    """Update user function"""
    model = Profile
    template_name = 'update_profile.html'
    form_class = ProfileForm

    def visitor_ip_address(self):
        """Get visitor IP"""
        x_forwarded_for = self.request.META.get('HTTP_X_FORWARDED_FOR')

        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = self.request.META.get('REMOTE_ADDR')
        return ip

    def get_success_url(self):
        """Return to profile in case the update was successful"""
        return reverse('profile:showprofile', kwargs={'pk': self.object.id})

    def get_queryset(self):
        """Allow the user to change only his own profile"""
        qs = super(UpdateProfile, self).get_queryset()
        return qs.filter(user=self.request.user)

    def form_valid(self, form):
        """Function to assign edit_ip"""
        instance = form.save(commit=False)
        # instance.edit_ip = self.request.META['REMOTE_ADDR']
        instance.edit_ip = self.visitor_ip_address()
        instance.save()
        return super().form_valid(form)


def main_page_redirect(request):
    if request.user.is_authenticated:
        response = redirect(reverse('profile:showprofile', args=(request.user.profile.id,)))
        return response
    else:
        response = redirect('/accounts/login/')
        return response

DjangoProject/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
            crossorigin="anonymous"></script>
    {% block head %}

    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container container-fluid">
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a style="padding:5px; margin-right:25px;" class="nav-link active display-6 px-2"
                           href="{% url 'profile:login' %}">Login</a>
                    </li>
                {% endif %}
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a style="padding:5px; margin-right:25px;" class="nav-link active display-6 px-2"
                       href="{% url 'profile:showprofile' pk=request.user.profile.id %}">My profile</a>
                </li>
                <li class="nav-item">
                    <a style="padding:5px; margin-left:25px;" class="nav-link active display-6 px-2"
                       href="{% url 'profile:updateprofile' pk=request.user.profile.id %}">Update profile</a>
                </li>
                <li class="nav-item">
                    <a style="padding:5px; margin-left:650px;" class="nav-link active display-6 px-2"
                       href="{% url 'profile:logout' %}">Logout</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div style="padding:20px; margin-top: 5px;" class="container container-fluid">
    {% block body_block %}{% endblock %}
</div>
</body>
</html>

DjangoProject/templates/show_profile.html
{% extends 'base.html' %}
{% load my_custom_tags %}
{% block body_block %}
{% if object %}
    <h3 class="display-3">Welcome back, {{ object.user }}</h3>
    <p class="font-monospace">{{ object.first_name }}</p>
    <p class="font-monospace">{{ object.last_name }}</p>
    <p class="font-monospace">{{ object.date_of_birth }}</p>
    <p class="font-monospace">{{ object.biography }}</p>
    <p class="font-monospace">{{ object.contacts }}</p>
    <p>
    Test tag with user instance: {% edit_list request.user %}</p>
    <p>Test tag with Profile instance: {% edit_list object %}</p>
    <p>Test tag with incorrect instnace: {% edit_list asdkaskd %}</p>
{% endif %}

{% endblock %}

DjangoProject/templates/update_profile.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <script type="text/javascript" src="/jsi18n/"></script>
    <script type="text/javascript" src="{% static 'admin/js/core.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/admin/RelatedObjectLookups.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/base.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/widgets.css' %}"/>
{% endblock %}
{% block body_block %}
    <form method="post">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button type="submit" class="btn btn-outline-dark">Update</button>
    </form>
{% endblock %}